<?php
class J_crmmaster extends CI_Model {

  function __construct(){
      parent::__construct();
  }
  
  function inventory_groups_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("crm/crm-master-ajax/inventory-groups-get-detail")."', {id_crm_inventory_groups: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.title = hasil.data.title;"
            . "formutama.id_crm_inventory_groups = hasil.data.id_crm_inventory_groups;"
            . "formutama.kode = hasil.data.kode;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function inventory_groups_delete(){
    $html = ""
      . "$(document).on('click', '.groups-delete', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/inventory-groups-delete")."', {id_crm_inventory_groups: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function inventory_groups_active(){
    $html = ""
      . "$(document).on('click', '.groups-active', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/inventory-groups-active")."', {id_crm_inventory_groups: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function satuan_groups_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("crm/crm-master-ajax/satuan-groups-get-detail")."', {id_crm_satuan_groups: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.title = hasil.data.title;"
            . "formutama.id_crm_satuan_groups = hasil.data.id_crm_satuan_groups;"
            . "formutama.code = hasil.data.code;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function satuan_groups_delete(){
    $html = ""
      . "$(document).on('click', '.groups-delete', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/satuan-groups-delete")."', {id_crm_satuan_groups: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function satuan_groups_active(){
    $html = ""
      . "$(document).on('click', '.groups-active', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/satuan-groups-active")."', {id_crm_satuan_groups: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function satuan_select_utama(){
    $html = ""
      . "function select_satuan(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("crm/crm-master-ajax/satuan-get-detail")."', {id_crm_satuan: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formsatuan.title = hasil.data.title;"
            . "formsatuan.id_crm_satuan = hasil.data.id_crm_satuan;"
            . "formsatuan.nilai = hasil.data.nilai;"
            . "formsatuan.level = hasil.data.level;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function satuan_delete(){
    $html = ""
      . "$(document).on('click', '.satuan-delete', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/satuan-delete")."', {id_crm_satuan: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_satuan.replace_items(hasil.data, hasil.data.id);"
            . "vm_satuan.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_satuan.cari($('#searchSatuan').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function satuan_active(){
    $html = ""
      . "$(document).on('click', '.satuan-active', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/satuan-active")."', {id_crm_satuan: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_satuan.replace_items(hasil.data, hasil.data.id);"
            . "vm_satuan.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_satuan.cari($('#searchSatuan').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function inventory_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("crm/crm-master-ajax/inventory-get-detail")."', {id_crm_inventory: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.title = hasil.data.title;"
            . "formutama.id_crm_inventory_groups = hasil.data.id_crm_inventory_groups;"
            . "formutama.id_crm_inventory = hasil.data.id_crm_inventory;"
            . "formutama.id_crm_satuan_groups = hasil.data.id_crm_satuan_groups;"
            . "formutama.code = hasil.data.code;"
            . "formutama.note = hasil.data.note;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function inventory_delete(){
    $html = ""
      . "$(document).on('click', '.inv-delete', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/inventory-delete")."', {id_crm_inventory: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function inventory_active(){
    $html = ""
      . "$(document).on('click', '.inv-active', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/inventory-active")."', {id_crm_inventory: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function storage_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("crm/crm-master-ajax/storage-get-detail")."', {id_crm_storage: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.title = hasil.data.title;"
            . "formutama.id_crm_storage = hasil.data.id_crm_storage;"
            . "formutama.code = hasil.data.code;"
            . "formutama.note = hasil.data.note;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function storage_delete(){
    $html = ""
      . "$(document).on('click', '.stdr-delete', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/storage-delete")."', {id_crm_storage: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function storage_active(){
    $html = ""
      . "$(document).on('click', '.stdr-active', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/storage-active")."', {id_crm_storage: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_utama.replace_items(hasil.data, hasil.data.id);"
            . "vm_utama.items_live[vm_utama.page.select[0]] = hasil.data;"
            . "vm_utama.cari($('#searchString').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function storage_inventory_set($grid){
    $html = ""
      . "$(document).on('click', '.inventory-set', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/storage-inventory-set")."', {id_crm_inventory: id, id_crm_storage: formutama.id_crm_storage}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.page.select = [];"
            . "{$grid['variable']}.page.select_value = '';"
            . "{$grid['variable']}.reselect();"

            . $this->global_format->js_grid_add($grid, "hasil.data")
            . "{$grid['variable']}.{$grid['cari']} = hasil.data.number;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function storage_inventory_unset($grid){
    $html = ""
      . "$(document).on('click', '.inventory-unset', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/storage-inventory-unset")."', {id_crm_storage_inventory: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.delete_items(id);"
            . "{$grid['variable']}.cari($('#searchInventory').val());"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function storage_inventory_hpp(){
    $html = ""
      . "$(document).on('click', '.inventory-hpp', function(evn){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("crm/crm-master-ajax/storage-inventory-hpp")."', {id_crm_storage_inventory: id, hpp: $('#hpp-'+id).val(), id_crm_satuan: $('#satuan-'+id).val()}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "$('#positif-response-title').html('".lang("Save")."');"
            . "$('#positif-response-body').html('".lang("Success")."');"
            . "$('#positif-response').modal('show');"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
}
?>
