<?php
class J_cms_master extends CI_Model {

  function __construct(){
      parent::__construct();
  }
  
  function banner_promo_form($grid){
    $html = ""
      . "var formutama = new Vue({"
        . "el: '#form-utama',"
        . "data: {"
          . "file: '',"
          . "link: '',"
          . "code: '',"
          . "title: '',"
          . "type: true,"
          . "startdate: '',"
          . "enddate: '',"
          . "sort: '',"
          . "note: '',"
          . "gambar: '',"
          . "id_cms_banner_promo: '',"
          . "editable: 'not-editable',"
        . "},"
        . "watch: {"
          . "type: function(val){"
            . "if(val == true){"
              . "this.editable = 'not-editable';"
            . "}"
            . "else{"
              . "this.editable = 'editable';"
            . "}"
          . "}"
        . "},"
        . "methods: {"
          . "upload: function(files){"
            . "var form_data = new FormData();"
            . "form_data.append('file', files[0]);"

            . "var upload = $.ajax({"
              . "url: '".site_url("cms/cms-ajax/banner-promo-file-upload")."',"
              . "dataType: 'text',"
              . "cache: false,"
              . "contentType: false,"
              . "processData: false,"
              . "data: form_data,"
              . "type: 'post',"
              . "async: false,"
              . "success: function(data){"
                . "return 'nbs';"
              . "}"
            . "}).responseText;"

            . "this.file = 'nbs';"
            . "if(upload){"
              . "this.file = $.parseJSON(upload);"
            . "}"

            . "if(this.file != 'nbs'){"
            . "}"
            . "else{"
              . "$('#negative-response-title').html('".lang("Upload")."');"
              . "$('#negative-response-body').html('".lang("Upload Failed")."');"
              . "$('#negative-response').modal('show');"
            . "}"
          . "},"
          . "update: function(){"
            . "$('#page-loading-post').show();"
            . "this.upload($('#file').prop('files'));"
//            . "var upp_hasil = $.parseJSON(upp);"
            . "if(!this.file.data && $('#file').prop('files').length > 0){"
              . "$('#negative-response-title').html('".lang("Function")."');"
              . "$('#negative-response-body').html('Upload Fail');"
              . "$('#negative-response').modal('show');"
              . "$('#page-loading-post').hide();"
            . "}"
            . "else{"
              . "$.post('".site_url("cms/cms-ajax/banner-promo-set")."', {file: this.file.data, type: this.type, link: this.link, code: this.code, title: this.title, startdate: this.startdate, enddate: this.enddate, note: this.note, sort: this.sort, id_cms_banner_promo: this.id_cms_banner_promo}, function(data){"
                . "var hasil = $.parseJSON(data);"
                . "if(hasil.status == 10001){"
                  . "$('#negative-response-title').html('".lang("Access")."');"
                  . "$('#negative-response-body').html('".lang("You can not access this function")."');"
                  . "$('#negative-response').modal('show');"
                . "}"
                . "else if(hasil.status == 3){"
                  . "$('#negative-response-title').html('".lang("Function")."');"
                  . "$('#negative-response-body').html(hasil.note);"
                  . "$('#negative-response').modal('show');"
                . "}"
                . "else{"
                  . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
                  . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
                  . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
                . "}"
              . "})"
              . ".done(function(){"
              . "})"
              . ".fail(function(){"
                . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
              . "})"
              . ".always(function(){"
                . "$('#page-loading-post').hide();"
              . "});"
            . "}"
          . "},"
          . "add_new: function(){"
            . "$('#page-loading-post').show();"
            . "this.upload($('#file').prop('files'));"
//            . "var upp_hasil = $.parseJSON(upp);"
            . "if(!this.file.data && $('#file').prop('files').length > 0){"
              . "$('#negative-response-title').html('".lang("Function")."');"
              . "$('#negative-response-body').html('Upload Fail');"
              . "$('#negative-response').modal('show');"
              . "$('#page-loading-post').hide();"
            . "}"
            . "else{"
              . "$.post('".site_url("cms/cms-ajax/banner-promo-set")."', {file: this.file.data, type: this.type, link: this.link, code: this.code, title: this.title, startdate: this.startdate, enddate: this.enddate, note: this.note, sort: this.sort}, function(data){"
                . "var hasil = $.parseJSON(data);"
                . "if(hasil.status == 10001){"
                  . "$('#negative-response-title').html('".lang("Access")."');"
                  . "$('#negative-response-body').html('".lang("You can not access this function")."');"
                  . "$('#negative-response').modal('show');"
                . "}"
                . "else if(hasil.status == 3){"
                  . "$('#negative-response-title').html('".lang("Function")."');"
                  . "$('#negative-response-body').html(hasil.note);"
                  . "$('#negative-response').modal('show');"
                . "}"
                . "else{"
                  . $this->global_format->js_grid_add($grid, "hasil.data")
                . "}"
              . "})"
              . ".done(function(){"
              . "})"
              . ".fail(function(){"
                . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
              . "})"
              . ".always(function(){"
                . "$('#page-loading-post').hide();"
              . "});"
            . "}"
          . "}"
        . "}"
      . "});"
      . "";
    return $html;
  }
  
  function banner_promo_delete($grid){
    $html = ""
      . "$(document).on('click', '.banner-delete', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("cms/cms-ajax/banner-promo-delete")."', {id_cms_banner_promo: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
    
  function banner_promo_active($grid){
    $html = ""
      . "$(document).on('click', '.banner-active', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("cms/cms-ajax/banner-promo-active")."', {id_cms_banner_promo: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
    
  function banner_promo_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("cms/cms-ajax/banner-promo-get-detail")."', {id: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.link = hasil.data.link;"
            . "formutama.title = hasil.data.title;"
            . "formutama.id_cms_banner_promo = hasil.data.id_cms_banner_promo;"
            . "formutama.code = hasil.data.code;"
            . "formutama.type = hasil.data.type;"
            . "formutama.sort = hasil.data.sort;"
            . "formutama.startdate = hasil.data.startdate;"
            . "formutama.enddate = hasil.data.enddate;"
            . "formutama.note = hasil.data.note;"
            . "formutama.gambar = hasil.data.gambar;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
}
?>
