<?php
class J_users_settings extends CI_Model {

  function __construct(){
      parent::__construct();
  }
  
  function group_teams_delete(){
    $html = ""
      . "$(document).on('click', '.teams-delete', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("users/users-settings-ajax/group-teams-delete")."', {id_m_users_group_teams: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_approval_employee.clear();"
//            . "vm_approval.clear();"
            . "vm_teams_employee.clear();"
            . "vm_teams.clear();"
            . "ambil_biodata_approval(0);"
            . "ambil_biodata_team(0);"
//            . "ambil_approval(0);"
            . "ambil_teams(0);"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function group_approval_delete(){
    $html = ""
      . "$(document).on('click', '.approval-delete', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("users/users-settings-ajax/group-approval-delete")."', {id_m_users_group_approval: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "vm_approval_employee.clear();"
            . "vm_approval.clear();"
            . "vm_teams_employee.clear();"
//            . "vm_teams.clear();"
            . "ambil_biodata_approval(0);"
            . "ambil_biodata_team(0);"
            . "ambil_approval(0);"
//            . "ambil_teams(0);"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function group_teams_save($grid_teams){
    $html = ""
      . "$(document).on('click', '.teams-save', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("users/users-settings-ajax/group-teams-set")."', {id_users: id, id_m_users_group: formutama.id_m_users_group}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . $this->global_format->js_grid_add($grid_teams, "hasil.data")
            . "vm_approval_employee.clear();"
            . "vm_teams_employee.clear();"
            . "ambil_biodata_approval(0);"
            . "ambil_biodata_team(0);"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function group_approval_save($grid_approval){
    $html = ""
      . "$(document).on('click', '.approval-save', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("users/users-settings-ajax/group-approval-set")."', {id_users: id, id_m_users_group: formutama.id_m_users_group}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "console.log(hasil);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . $this->global_format->js_grid_add($grid_approval, "hasil.data")
            . "vm_approval_employee.clear();"
            . "vm_teams_employee.clear();"
            . "ambil_biodata_approval(0);"
            . "ambil_biodata_team(0);"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function group_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("users/users-settings-ajax/group-get-detail")."', {id: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.title = hasil.data.title;"
            . "formutama.code = hasil.data.code;"
            . "formutama.id_m_users_group = hasil.data.id_m_users_group;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function session_users_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("users/users-settings-ajax/session-users-set")."', {id_users: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
          . "}"
        . "})"
        . ".done(function(){"
//          . "console.log(vm_utama);"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function session_group_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("users/users-settings-ajax/session-group-set")."', {id_m_users_group: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
          . "}"
        . "})"
        . ".done(function(){"
//          . "console.log(vm_utama);"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
}
?>
