<?php
class J_request extends CI_Model {

  function __construct(){
      parent::__construct();
  }
  
  function recomendation_form($inventory_dropdown, $grid){
    $param_items = array(
      "type"        => true,
      "id_scm_satuan"   => "",
      "id_scm_satuan_temp"=> "",
      "id_scm_inventory"=> "",
      "options_satuan"  => array(),
      "options_inventory"=> $inventory_dropdown,
      
      "inventory" => "",
      "urut" => "",
      "qty" => "",
      "satuan" => "",
      "desc" => "",
      "note" => "",
    );
    $data = json_encode($param_items);
    $html = ""
      . "var recomendation = new Vue({"
        . "el: '#form-recomendation',"
        . "data: {$data},"
        . "watch: {"
          . "id_scm_inventory: function(val){"
            . "var vuejs = this;"
            . "$.post('".site_url("scmprocurement/request-ajax/monitoring-request-satuan-dropdown")."', {id_scm_inventory: val}, function(data){"
              . "var hasil = $.parseJSON(data);"
              . "if(hasil.status == 10001){"
                . "$('#negative-response-title').html('".lang("Access")."');"
                . "$('#negative-response-body').html('".lang("You can not access this function")."');"
                . "$('#negative-response').modal('show');"
              . "}"
              . "else if(hasil.status == 3){"
                . "$('#negative-response-title').html('".lang("Function")."');"
                . "$('#negative-response-body').html(hasil.note);"
                . "$('#negative-response').modal('show');"
              . "}"
              . "else{"
                . "vuejs.options_satuan = hasil.data;"
              . "}"
            . "})"
            . ".fail(function(){"
              . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
            . "})"
            . ".always(function(){"
              . "vuejs.id_scm_satuan = vuejs.id_scm_satuan_temp;"
            . "});"
          . "}"
        . "},"
        . "methods: {"
          . "update: function(){"
            . "$('#page-loading-recomendation').show();"
            . "var kirim = {"
              . "type: this.type,"
              . "id_scm_satuan: this.id_scm_satuan,"
              . "id_scm_inventory: this.id_scm_inventory,"
              . "id_scm_procurement_request_items: formitems.id_scm_procurement_request_items,"
              . "inventory: this.inventory,"
              . "qty: this.qty,"
              . "urut: this.urut,"
              . "satuan: this.satuan,"
              . "desc: this.desc,"
              . "note: this.note"
            . "};"
            . "$.post('".site_url("scmprocurement/request-ajax/recomendation-set")."', kirim, function(data){"
              . "var hasil = $.parseJSON(data);"
              . "if(hasil.status == 10001){"
                . "$('#negative-response-title').html('".lang("Access")."');"
                . "$('#negative-response-body').html('".lang("You can not access this function")."');"
                . "$('#negative-response').modal('show');"
              . "}"
              . "else if(hasil.status == 3){"
                . "$('#negative-response-title').html('".lang("Function")."');"
                . "$('#negative-response-body').html(hasil.note);"
                . "$('#negative-response').modal('show');"
              . "}"
              . "else if(hasil.status == 2 || hasil.status == '2'){"
                . $this->global_format->js_grid_add($grid, "hasil.data")
              . "}"
              . "else{"
              . "}"
            . "})"
            . ".fail(function(){"
              . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
            . "})"
            . ".always(function(){"
              . "$('#page-loading-recomendation').hide();"
            . "});"
          . "}"
        . "}"
      . "});"
      . "";
    return $html;
  }
  
  function recomendation_inventory_form(){
    $param_items = array(
      "title"                     => "",
      "sku"                       => "",
      "id_scm_inventory_category" => "",
      "id_scm_inventory_brand"    => "",
      "id_scm_satuan_group"       => "",
      "type"                      => "",
    );
    $data = json_encode($param_items);
    $html = ""
      . "var forminventory = new Vue({"
        . "el: '#form-inventory',"
        . "data: {$data},"
        . "watch: {"
        . "},"
        . "methods: {"
          . "submit: function(){"
            . "var kirim = {"
              . "title: this.title,"
              . "sku: this.sku,"
              . "id_scm_inventory_category: this.id_scm_inventory_category,"
              . "id_scm_inventory_brand: this.id_scm_inventory_brand,"
              . "id_scm_satuan_group: this.id_scm_satuan_group,"
              . "type: this.type"
            . "};"
            . "$.post('".site_url("scmprocurement/request-ajax/recomendation-inventory-set")."', kirim, function(data){"
              . "var hasil = $.parseJSON(data);"
              . "if(hasil.status == 10001){"
//                . "$('#negative-response-title').html('".lang("Access")."');"
//                . "$('#negative-response-body').html('".lang("You can not access this function")."');"
//                . "$('#negative-response').modal('show');"
              . "}"
              . "else if(hasil.status == 3){"
//                . "$('#negative-response-title').html('".lang("Function")."');"
//                . "$('#negative-response-body').html(hasil.note);"
//                . "$('#negative-response').modal('show');"
              . "}"
              . "else if(hasil.status == 2 || hasil.status == '2'){"
                . $this->global_format->js_grid_add($grid, "hasil.data")
              . "}"
              . "else{"
              . "}"
            . "})"
            . ".fail(function(){"
              . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
            . "})"
            . ".always(function(){"
              . "$('#page-loading-recomendation').hide();"
            . "});"
          . "}"
        . "}"
      . "});"
      . "";
    return $html;
  }
  
  function request_select_utama(){
    $html = ""
      . "function select_utama(){"
        . "var id = vm_utama.page.select_value;"
        . "$.post('".site_url("scmprocurement/request-ajax/request-get-detail")."', {id: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formutama.title = hasil.data.title;"
            . "formutama.id_scm_procurement_request = hasil.data.id_scm_procurement_request;"
            . "formutama.note = hasil.data.note;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function request_select_items(){
    $html = ""
      . "function select_items(){"
        . "var id = vm_items.page.select_value;"
        . "$.post('".site_url("scmprocurement/request-ajax/request-items-get-detail")."', {id: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formitems.title = hasil.data.title;"
            . "formitems.id_scm_procurement_request_items = hasil.data.id_scm_procurement_request_items;"
            . "formitems.qty = hasil.data.qty;"
            . "formitems.satuan = hasil.data.satuan;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function monitoring_request_select_items(){
    $html = ""
      . "function select_items(){"
        . "var id = vm_items.page.select_value;"
        . "$.post('".site_url("scmprocurement/request-ajax/monitoring-request-items-get-detail")."', {id: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "formitems.title = hasil.data.title;"
            . "formitems.id_scm_procurement_request_items = hasil.data.id_scm_procurement_request_items;"
            . "formitems.qty = hasil.data.qty;"
            . "formitems.satuan = hasil.data.satuan;"
            . "formitems.id_scm_inventory = hasil.data.id_scm_inventory;"
            . "formitems.qty_real = hasil.data.qty_real;"
            . "formitems.recomendation = hasil.data.recomendation;"
            . "formitems.id_scm_satuan = hasil.data.id_scm_satuan;"
            . "formitems.id_scm_satuan_temp = hasil.data.id_scm_satuan;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function recomendation_select(){
    $html = ""
      . "function select_recomendation(){"
        . "var id = vm_recomendation.page.select_value;"
        . "$.post('".site_url("scmprocurement/request-ajax/recomendation-get-detail")."', {id: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "recomendation.type = hasil.data.type;"
            . "recomendation.id_scm_satuan = hasil.data.id_scm_satuan;"
            . "recomendation.id_scm_satuan_temp = hasil.data.id_scm_satuan;"
            . "recomendation.id_scm_inventory = hasil.data.id_scm_inventory;"
            . "recomendation.inventory = hasil.data.inventory;"
            . "recomendation.urut = hasil.data.urut;"
            . "recomendation.qty = hasil.data.qty;"
            . "recomendation.satuan = hasil.data.satuan;"
            . "recomendation.desc = hasil.data.desc;"
            . "recomendation.note = hasil.data.note;"
          . "}"
        . "})"
        . ".done(function(){"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "}"
      . "";
    return $html;
  }
  
  function request_submitted($grid){
    $html = ""
      . "$(document).on('click', '.request-submitted', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/request-submitted")."', {id_scm_procurement_request: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function request_accepted($grid){
    $html = ""
      . "$(document).on('click', '.request-accepted', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/request-accepted")."', {id_scm_procurement_request: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function request_rejected($grid){
    $html = ""
      . "$(document).on('click', '.request-rejected', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/request-rejected")."', {id_scm_procurement_request: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function request_items_delete($grid){
    $html = ""
      . "$(document).on('click', '.items-delete', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/request-items-delete")."', {id_scm_procurement_request_items: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.delete_items(id);"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function monitoring_request_items_delete($grid, $grid2){
    $html = ""
      . "$(document).on('click', '.items-delete', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/monitoring-request-items-delete")."', {id_scm_procurement_request_items: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
            
            . "{$grid2['variable']}.replace_items(hasil.data2, hasil.data2.id);"
            . "{$grid2['variable']}.items_live[{$grid2['variable']}.page.select[0]] = hasil.data2;"
            . "{$grid2['variable']}.cari($('#{$grid2['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function monitoring_request_items_process($grid, $grid2){
    $html = ""
      . "$(document).on('click', '.items-process', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/monitoring-request-items-process")."', {id_scm_procurement_request_items: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
            
            . "{$grid2['variable']}.replace_items(hasil.data2, hasil.data2.id);"
            . "{$grid2['variable']}.items_live[{$grid2['variable']}.page.select[0]] = hasil.data2;"
            . "{$grid2['variable']}.cari($('#{$grid2['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function recomendation_request_items_process($grid, $grid2){
    $html = ""
      . "$(document).on('click', '.items-process', function(evt){"
        . "$(this).hide();"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/recomendation-items-process")."', {id_scm_procurement_request_items: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
            
            . "{$grid2['variable']}.clear();"
            . "ambil_recomendation(0);"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
  function recomendation_pilih($grid, $grid2, $grid3){
    $html = ""
      . "$(document).on('click', '.recomendation-pilih', function(evt){"
        . "var id = $(this).attr('isi');"
        . "var type = $(this).attr('isi2');"
        . "if(type == 2 || type == '2'){"
          . "$('#recomendation-inventory').modal('show');"
        . "}"
        . "else{"
          . "$(this).hide();"
          . "$.post('".site_url("scmprocurement/request-ajax/recomendation-items-pilih")."', {id_scm_procurement_request_items_recomendation: id}, function(data){"
            . "var hasil = $.parseJSON(data);"
            . "if(hasil.status == 10001){"
              . "$('#negative-response-title').html('".lang("Access")."');"
              . "$('#negative-response-body').html('".lang("You can not access this function")."');"
              . "$('#negative-response').modal('show');"
            . "}"
            . "else if(hasil.status == 3){"
              . "$('#negative-response-title').html('".lang("Function")."');"
              . "$('#negative-response-body').html(hasil.note);"
              . "$('#negative-response').modal('show');"
            . "}"
            . "else{"
              . "if(hasil.pilih == 2){"
                . "{$grid3['variable']}.delete_items(hasil.id_scm_procurement_request);"
                . "{$grid3['variable']}.cari($('#{$grid3['cari']}').val());"
                . "{$grid['variable']}.clear();"
                . "{$grid2['variable']}.clear();"
              . "}"
              . "else{"
                . "{$grid['variable']}.clear();"
                . "ambil_recomendation(0);"

                . "{$grid2['variable']}.replace_items(hasil.data2, hasil.data2.id);"
                . "{$grid2['variable']}.items_live[{$grid2['variable']}.page.select[0]] = hasil.data2;"
                . "{$grid2['variable']}.cari($('#{$grid2['cari']}').val());"
              . "}"

            . "}"
          . "})"
          . ".fail(function(){"
            . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
          . "})"
          . ".always(function(){"
          . "});"
        . "}"
      . "});"
      . "";
    return $html;
  }
  
  function monitoring_request_delete($grid){
    $html = ""
      . "$(document).on('click', '.request-delete', function(evt){"
        . "var id = $(this).attr('isi');"
        . "$.post('".site_url("scmprocurement/request-ajax/monitoring-request-delete")."', {id_scm_procurement_request: id}, function(data){"
          . "var hasil = $.parseJSON(data);"
          . "if(hasil.status == 10001){"
            . "$('#negative-response-title').html('".lang("Access")."');"
            . "$('#negative-response-body').html('".lang("You can not access this function")."');"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else if(hasil.status == 3){"
            . "$('#negative-response-title').html('".lang("Function")."');"
            . "$('#negative-response-body').html(hasil.note);"
            . "$('#negative-response').modal('show');"
          . "}"
          . "else{"
            . "{$grid['variable']}.replace_items(hasil.data, hasil.data.id);"
            . "{$grid['variable']}.items_live[{$grid['variable']}.page.select[0]] = hasil.data;"
            . "{$grid['variable']}.cari($('#{$grid['cari']}').val());"
          . "}"
        . "})"
        . ".fail(function(){"
          . "alert('".lang("Fail").": ".lang("Please check your internet connection")."');"
        . "})"
        . ".always(function(){"
        . "});"
      . "});"
      . "";
    return $html;
  }
  
}
?>
